exports.DOCUMENT =
{
  "meta":{
  "name" : "Draft article in review",
  },
  "sections":[
    {"type" : "text", "formatting" : "heading", "level" : "1", "alignment" : "center", "content" : "Testing draft article",
      "expected_content" : "Testing draft article"},
    {"type" : "text", "formatting" : "heading", "level" : "1", "alignment" : "center", "content" : "String Theory’s Weirdest Ideas Finally Make Sense—Thanks to VR",
      "expected_content" : "String Theory’s Weirdest Ideas Finally Make Sense—Thanks to VR"},
    // {"type" : "picture", "path" :  "/workspace/autotests/provisions/img/article1/pic_1.jpg"},
    {"type" : "text", "formatting" : "paragraph", "styles" : ["italic"], "content" : "THE ROBOT IS building a tesseract. He motions at a glowing cube floating before him, and an identical cube emerges. He drags it to the left, but the two cubes stay connected, strung together by glowing lines radiating from their corners. The robot lowers its hands, and the cubes coalesce into a single shape—with 24 square faces, 16 vertices, and eight connected cubes existing in four dimensions. A tesseract.",
      "expected_content" : "THE ROBOT IS building a tesseract. He motions at a glowing cube floating before him, and an identical cube emerges. He drags it to the left, but the two cubes stay connected, strung together by glowing lines radiating from their corners. The robot lowers its hands, and the cubes coalesce into a single shape—with 24 square faces, 16 vertices, and eight connected cubes existing in four dimensions. A tesseract."},
    {"type" : "text", "formatting" : "paragraph", "styles" : ["bold", "italic", "underline"], "content" : "This isn’t a video game. It’s a classroom. And the robot is @, a physicist at Columbia University and bestselling author of several popular science books. His robot avatar teaches a semicircle of student robots, each wearing a shoulder badge of their home country’s flag. The classroom is outer space: Greene and the arc of student-robots orbit Earth. After he shows the students the  tesseract, Greene directs his class to try making four, five, even six dimension objects. This is a virtual reality course on string theory; the lesson happens to be about objects with more than three dimensions.",
      "anchors":[{"type" : "weblink", "name" : "Brian Greene", "address" : "https://www.wired.com/2017/05/brian-greene-science-becames-political-prisoner/"}],
      "expected_content" : "This isn’t a video game. It’s a classroom. And the robot is Brian Greene, a physicist at Columbia University and bestselling author of several popular science books. His robot avatar teaches a semicircle of student robots, each wearing a shoulder badge of their home country’s flag. The classroom is outer space: Greene and the arc of student-robots orbit Earth. After he shows the students the  tesseract, Greene directs his class to try making four, five, even six dimension objects. This is a virtual reality course on string theory; the lesson happens to be about objects with more than three dimensions."},
    {"type" : "text", "formatting" : "paragraph","alignment" : "right", "content" : "In real life, Greene is wearing a dark blue shirt, black jeans, and boots, and his normal, non-hovering chair is sitting in a concrete-floored VR business called Step Into the Light planted firmly on Earth’s surface—Manhattan’s Lower East Side. An HTC Vive headset covers his face, and he gestures effusively—he’s a New York native—with the controllers.",
      "expected_content" : "In real life, Greene is wearing a dark blue shirt, black jeans, and boots, and his normal, non-hovering chair is sitting in a concrete-floored VR business called Step Into the Light planted firmly on Earth’s surface—Manhattan’s Lower East Side. An HTC Vive headset covers his face, and he gestures effusively—he’s a New York native—with the controllers."},
    {"type" : "text", "formatting" : "paragraph", "styles" : ["underline"], "content" : "Greene is teaching this futuristic class as part of the @, a week-long, city-wide celebration of intellect and curiosity. He’s actually a co-founder, along with documentarian Tracy Day. In addition to VR classrooms, it features panel discussions on the future of AI, chemistry-themed cooking demonstrations, and ride-alongs with rat scientists. There are events in every borough. Also, cyberspace—and apparently extradimensional space, too.",
      "anchors":[{"type" : "weblink", "name" : "World Science Festival", "address" : "http://www.worldsciencefestival.com/festival/world-science-festival-2017/"}],
      "expected_content" : "Greene is teaching this futuristic class as part of the World Science Festival, a week-long, city-wide celebration of intellect and curiosity. He’s actually a co-founder, along with documentarian Tracy Day. In addition to VR classrooms, it features panel discussions on the future of AI, chemistry-themed cooking demonstrations, and ride-alongs with rat scientists. There are events in every borough. Also, cyberspace—and apparently extradimensional space, too."},
    {"type" : "text", "formatting" : "paragraph", "indent" : "1", "styles" : ["italic"], "content" : "Extra dimensions are a critical part of Greene’s field of study. @ that the universe is built not just from three spatial dimensions (up/down, side/side, forward/backward) and the single dimension of time, but at least six other dimensions. These extra dimensions would be too small for humans to detect—about 10-33 centimeters. But, according to the theory, the six, curled up dimensions play a major role in controlling how subatomic strings vibrate, and those vibrations determine how quarks, electrons, and other fundamental particles behave. Ultimately, these phenomenon scale up to explain modern how gravity and quantum mechanics fit together: Otherwise known as The Biggest Question in Physics. “String theory,” says Greene, “is speculative and hypothetical, but mathematically quite compelling.”",
      "anchors":[{"type" : "weblink", "name" : "String theory posits", "address" : "http://superstringtheory.com/"}],
         "expected_content" : "Extra dimensions are a critical part of Greene’s field of study. String theory posits that the universe is built not just from three spatial dimensions (up/down, side/side, forward/backward) and the single dimension of time, but at least six other dimensions. These extra dimensions would be too small for humans to detect—about 10-33 centimeters. But, according to the theory, the six, curled up dimensions play a major role in controlling how subatomic strings vibrate, and those vibrations determine how quarks, electrons, and other fundamental particles behave. Ultimately, these phenomenon scale up to explain modern how gravity and quantum mechanics fit together: Otherwise known as The Biggest Question in Physics. “String theory,” says Greene, “is speculative and hypothetical, but mathematically quite compelling.”"},
    // {"type" : "picture", "path" :  "/workspace/autotests/provisions/img/article1/pic_2.jpg"},
    {"type" : "table", "content" :[["City", "Population", "Area", "GDP", "Square"], ["London", 11, 12, 13, 14], ["Paris", 21, 22, 23, 24], ["Berlin", 31, 32, 33, 34], ["Kiev", 41, 42, 43, 44]], "caption" : "Selenium table"},
    {"type" : "text", "formatting" : "list-ol", "indent" : "1", "content" : "It’s also quite confusing. Those six extra dimensions some string theorists predict come wrapped together in what are known as Calabi-Yau manifolds. Greene is a great writer—bestselling, even—but even he can’t perfectly explain what these things look like. VR helps him make the shapes make sense. Sort of. Greene brings up a video of a wire in the virtual reality space. To a human, he says, this is a two dimensional object: a line. The video zooms in, and something new appears: an ant, walking in a circle around the wire’s girth. The lesson here is that extra dimensions are invisible unless you are the right size to see them.",
      "expected_content" : "It’s also quite confusing. Those six extra dimensions some string theorists predict come wrapped together in what are known as Calabi-Yau manifolds. Greene is a great writer—bestselling, even—but even he can’t perfectly explain what these things look like. VR helps him make the shapes make sense. Sort of. Greene brings up a video of a wire in the virtual reality space. To a human, he says, this is a two dimensional object: a line. The video zooms in, and something new appears: an ant, walking in a circle around the wire’s girth. The lesson here is that extra dimensions are invisible unless you are the right size to see them."},
    {"type" : "text", "formatting" : "paragraph-ol", "level" : "2", "styles" : ["bold"], "alignment" : "center", "content" : "The analogy with the wire makes sense, but it doesn’t scratch all the strangeness away from trying to visualize six dimensional curling. Greene goes on to explain that humans would need microscopes capable of peering inside the smallest particles in order to observe the curled-up dimensions. As he does, the virtual classroom passes through a series of grids—this is to represent shrinking—until everyone is small enough to directly observe the six dimensional Calabi-Yau manifolds that exist at reality’s most minuscule junctures.",
      "expected_content" : "The analogy with the wire makes sense, but it doesn’t scratch all the strangeness away from trying to visualize six dimensional curling. Greene goes on to explain that humans would need microscopes capable of peering inside the smallest particles in order to observe the curled-up dimensions. As he does, the virtual classroom passes through a series of grids—this is to represent shrinking—until everyone is small enough to directly observe the six dimensional Calabi-Yau manifolds that exist at reality’s most minuscule junctures."},
    {"type" : "text", "formatting" : "paragraph-ol", "level" : "2", "styles" : ["italic"], "alignment" : "justify", "content" : "The lesson—designed by Abelana VR productions—is nearly over. Greene reiterates to his students that the extra-dimensional weirdness they spent the past hour exploring together is mostly mathematical conjecture. The classroom scales back up, and now is floating in front of a supermassive black hole.",
      "expected_content" : "The lesson—designed by Abelana VR productions—is nearly over. Greene reiterates to his students that the extra-dimensional weirdness they spent the past hour exploring together is mostly mathematical conjecture. The classroom scales back up, and now is floating in front of a supermassive black hole."},
    {"type" : "text", "formatting" : "paragraph-ol", "level" : "2", "styles" : ["underline"], "alignment" : "right", "content" : "Still wearing his headset, Greene opens up the floor for questions. One student, from Denmark, asks, “How does it feel to be teaching in the next step of education?” As Greene answers—about how it’s so wonderful that people from around the globe can gather and share complex ideas like this—a student flings a virtual tesseract at the teacher’s head. Next step, indeed.",
      "expected_content" : "Still wearing his headset, Greene opens up the floor for questions. One student, from Denmark, asks, “How does it feel to be teaching in the next step of education?” As Greene answers—about how it’s so wonderful that people from around the globe can gather and share complex ideas like this—a student flings a virtual tesseract at the teacher’s head. Next step, indeed."}
  ]
};
