exports.DOCUMENT =
{
  "meta":{
  "name" : "SMASHDOCs selenium automation project",
  "description": "This document is created and filled automatically by selenium-webdriver.",
  "tags"  : ["autotests", "QA","feature validation"]
  },
  "sections":[
    {"type" : "text", "formatting" : "paragraph", "styles" : ["bold", "italic"], "alignment" : "right", "content" : "Andrii Prykhodko", "expected_content" : "Andrii Prykhodko"},
    {"type" : "text", "formatting" : "paragraph", "styles" : ["bold"], "alignment" : "right", "content" : "QA Lead at Smashdocs", "expected_content" : "QA Lead at Smashdocs"},
    {"type" : "text", "formatting" : "paragraph", "styles" : ["italic"], "alignment" : "right", "content" : "2016-2017", "expected_content" : "2016-2017"},
    {"type" : "text", "formatting" : "heading", "level" : "1", "styles" : ["underline"], "alignment" : "center", "content" : "SMASHDOCs test automation project", "expected_content" : "SMASHDOCs test automation project"},
    {"type" : "text", "formatting" : "heading-ol", "level" : "1", "alignment" : "center", "content" : "Covered features:", "expected_content" : "Covered features:"},
    {"type" : "text", "formatting" : "paragraph-ol", "level" : "2", "styles" : ["bold"], "content" : "Registration", "expected_content" : "Registration"},
    {"type" : "text", "formatting" : "paragraph-ol", "level" : "2", "styles" : ["bold"], "content" : "Login", "expected_content" : "Login"},
    {"type" : "text", "formatting" : "paragraph-ol", "level" : "2", "styles" : ["bold"], "content" : "Create document", "expected_content" : "Create document"},
    {"type" : "text", "formatting" : "paragraph-ol", "level" : "2", "styles" : ["bold"], "content" : "Import document", "expected_content" : "Import document"},
    {"type" : "text", "formatting" : "paragraph-ol", "level" : "2", "styles" : ["bold"], "content" : "Set document to review", "expected_content" : "Set document to review"},
    {"type" : "text", "formatting" : "paragraph-ol", "level" : "2", "styles" : ["bold"], "content" : "Send document to trash", "expected_content" : "Send document to trash"},
    {"type" : "text", "formatting" : "paragraph-ol", "level" : "2", "styles" : ["bold"], "content" : "Create section:", "expected_content" : "Create section:"},
    {"type" : "text", "formatting" : "list", "indent" : "1", "content" : "Heading", "expected_content" : "Heading"},
    {"type" : "text", "formatting" : "list", "indent" : "1", "content" : "Numbered heading", "expected_content" : "Numbered heading"},
    {"type" : "text", "formatting" : "list", "indent" : "1", "content" : "Paragraph", "expected_content" : "Paragraph"},
    {"type" : "text", "formatting" : "list", "indent" : "1", "content" : "Numbered paragraph", "expected_content" : "Numbered paragraph"},
    {"type" : "text", "formatting" : "list", "indent" : "1", "content" : "Numbered list", "expected_content" : "Numbered list"},
    {"type" : "text", "formatting" : "list", "indent" : "1", "content" : "List", "expected_content" : "List"},
    {"type" : "text", "formatting" : "list", "indent" : "1", "content" : "Table", "expected_content" : "Table"},
    {"type" : "text", "formatting" : "list", "indent" : "1", "content" : "Image", "expected_content" : "Image"},
    {"type" : "text", "formatting" : "paragraph-ol", "level" : "2", "styles" : ["bold"], "content" : "Apply styles:", "expected_content" : "Apply styles:"},
    {"type" : "text", "formatting" : "list", "indent" : "1", "styles" : ["bold"], "content" : "Bold", "expected_content" : "Bold"},
    {"type" : "text", "formatting" : "list", "indent" : "1", "styles" : ["italic"], "content" : "Italic", "expected_content" : "Italic"},
    {"type" : "text", "formatting" : "list", "indent" : "1", "styles" : ["underline"], "content" : "Underline", "expected_content" : "Underline"},
    {"type" : "text", "formatting" : "paragraph-ol", "level" : "2", "styles" : ["bold"], "content" : "Apply alignment:", "expected_content" : "Apply alignment:"},
    {"type" : "text", "formatting" : "list", "indent" : "1", "content" : "Right", "expected_content" : "Right"},
    {"type" : "text", "formatting" : "list", "indent" : "1", "content" : "Left", "expected_content" : "Left"},
    {"type" : "text", "formatting" : "list", "indent" : "1", "content" : "Center", "expected_content" : "Center"},
    {"type" : "text", "formatting" : "list", "indent" : "1", "content" : "Justify", "expected_content" : "Justify"},
    {"type" : "text", "formatting" : "paragraph-ol", "level" : "2", "styles" : ["bold"], "content" : "Insert anchors:", "expected_content" : "Insert anchors:"},
    {"type" : "text", "formatting" : "list", "indent" : "1", "content" : "@",
    "anchors" : [{"type" : "weblink", "name" : "Weblinks", "address" : "https://google.com" }],
    "expected_content" : "Weblinks"},
    {"type" : "text", "formatting" : "list", "indent" : "1", "content" : "Footnotes@",
    "anchors" : [{"type" : "footnote", "content" : "Selenium notes..."}],
    "expected_content" : "Footnotes1"},
    {"type" : "text", "formatting" : "list", "indent" : "1", "content" : "Cross-references@",
    "anchors" : [{"type" : "crossRef", "item" : "2" }],
    "expected_content" : "Cross-references1"},
    {"type" : "text", "formatting" : "paragraph-ol", "level" : "2", "styles" : ["bold"], "content" : "Apply indents/outdents", "expected_content" : "Apply indents/outdents"},
    {"type" : "text", "formatting" : "paragraph-ol", "level" : "2", "styles" : ["bold"], "content" : "Saving content", "expected_content" : "Saving content"},
    {"type" : "text", "formatting" : "paragraph-ol", "level" : "2", "styles" : ["bold"], "content" : "Redline:", "expected_content" : "Redline:"},
    {"type" : "text", "formatting" : "list", "indent" : "1", "content" : "Text@Text",
    "anchors" : [{"type" : "weblink", "name" : "ẞабЪγλώσ”№%,.;()_+=|&#?<>~’", "address" : "https://google.com" }],
    "expected_content": "TextẞабЪγλώσ”№%,.;()_+=|&#?<>~’Text" },
    {"type" : "text", "formatting" : "paragraph-ol", "level" : "1", "content" : "Text@ Text",
    "anchors" : [{"type" : "weblink", "name" : "Āā@ĎđĐďð ØøŒœŔŕŘř", "address" : "https://google.com" }],
    "expected_content": "TextĀā@ĎđĐďð ØøŒœŔŕŘř Text" },
    {"type" : "text", "formatting" : "heading-ol", "level" : "1", "content" : "Text @Text",
    "anchors" : [ {"type" : "weblink", "name" : "¡¿ÄäÀàÁá ÂâÃãÅåǍǎĄą ĂăÆæ", "address" : "https://google.com" }],
    "expected_content": "Text ¡¿ÄäÀàÁá ÂâÃãÅåǍǎĄą ĂăÆæText" },
    {"type" : "text", "formatting" : "paragraph", "content" : "Text,@Text",
    "anchors" : [ {"type" : "weblink", "name" : "¡¿Äaakаватар", "address" : "https://google.com" }],
    "expected_content": "Text,¡¿ÄaakаватарText" },
    {"type" : "text", "formatting" : "list-ol", "content" : "Text@,Text",
    "anchors" : [ {"type" : "weblink", "name" : ")_+=|&#?<a>~âÃãÅ", "address" : "https://google.com" }],
    "expected_content": "Text)_+=|&#?<a>~âÃãÅ,Text" },
    {"type" : "text", "formatting" : "list-ol", "indent" : "1", "content" : "Text@. Text",
    "anchors" : [ {"type" : "crossRef", "item" : "1" }],
    "expected_content" : "TextSMASHDOCs test automation project. Text"},
    {"type" : "text", "formatting" : "heading-ol", "level" : "1", "alignment" : "center", "content" : "Testing article", "expected_content" : "Testing article"},
    {"type" : "text", "formatting" : "paragraph", "content" : "GOOGLE RULES SEARCH and excels at turning your searches into ad revenue. Its ability to convince people that its way of advertising is best helped make it the world’s second most valuable company. But the ad industry is starting to doubt that.",
    "expected_content" : "GOOGLE RULES SEARCH and excels at turning your searches into ad revenue. Its ability to convince people that its way of advertising is best helped make it the world’s second most valuable company. But the ad industry is starting to doubt that."},
    // {"type" : "picture", "path" :  "/workspace/autotests/provisions/img/article2/GoogleAd.jpg"},
    {"type" : "text", "formatting" : "paragraph", "content" : "Repeated instances of flawed or false reporting has marketers pushing digital platforms for @ about whether ads appear as planned and whether people actually see them. The tech sector is beginning to respond. Today, Google said an @ will vet its processes to ensure advertisers get what they pay@ for.",
              "anchors" : [ {"type" : "weblink", "name" : "greater transparency", "address" : "https://www.wired.com/2016/11/facebooks-stumbles-expose-flaws-plan-rule-advertising/" }, { "type" : "weblink", "name" : "auditor" , "address" : "http://agency.googleblog.com/2017/02/building-trust-and-increasing.html" }, {"type" : "footnote", "content" : "Selenium notes..."}],
              "expected_content": "Repeated instances of flawed or false reporting has marketers pushing digital platforms for greater transparency about whether ads appear as planned and whether people actually see them. The tech sector is beginning to respond. Today, Google said an auditor will vet its processes to ensure advertisers get what they pay2 for."
    },
    {"type" : "text", "formatting" : "paragraph", "content" : "Google plans to let the Media Rating Council see how third-party ad-measurement companies gather data on YouTube ad performance. The council will also get access to data for ads placed on sites across the web through Google’s two automated ad-buying platforms, AdWords and DoubleClick Bid Manager.",
    "expected_content" : "Google plans to let the Media Rating Council see how third-party ad-measurement companies gather data on YouTube ad performance. The council will also get access to data for ads placed on sites across the web through Google’s two automated ad-buying platforms, AdWords and DoubleClick Bid Manager."},
    {"type" : "text", "formatting" : "paragraph", "alignment" : "justify", "content" : "Google and Facebook dominate the digital ad industry, accounting for @ of all spending in the US. Analysts estimate @ of all US ad spending goes to digital now and will rise to nearly half by 2020. In this marketplace, @ of all, garnering ninety percent of its revenue from ads.",
              "anchors" : [ {"type" : "weblink", "name" : "more than two-thirds" , "address" : "https://www.bloomberg.com/gadfly/articles/2016-11-21/google-and-facebook-divide-up-your-advertising-viewing" }, {"type" : "weblink", "name" : "more than one-third" , "address" : "https://www.emarketer.com/Report/US-Ad-Spending-eMarketers-Updated-Estimates-Forecast-20152020/2001915" }, {"type" : "weblink", "name" : "Google is the biggest winner" , "address" : "https://www.wired.com/2017/01/google-goes-bad-ads-bad-sites-profit/" }],
              "expected_content": "Google and Facebook dominate the digital ad industry, accounting for more than two-thirds of all spending in the US. Analysts estimate more than one-third of all US ad spending goes to digital now and will rise to nearly half by 2020. In this marketplace, Google is the biggest winner of all, garnering ninety percent of its revenue from ads."
    },
    {"type" : "table", "content" :[["City", "Population m", "Urban area km^2", "GDP $bn", "Elevation m"], ["London", "9.787", "1 737.9", "565", "35"], ["Paris", "12.476", "2 845", "624", "131"], ["Berlin", "3,670", "891.7", "152", "34"], ["Kiev", "2,804", "839", "12.192", "179"]], "caption" : "Selenium table"},
    {"type" : "text", "formatting" : "paragraph", "content" : "But this dominance has led to steadily increasing concern that advertisers themselves haven’t been able to independently evaluate Google’s reports of how ads perform on Google. Grading one’s own homework is problematic, critics say, because Google and Facebook both sell ads and give their partners the data to assess how well those ads may or may not be working. Advertisers can deploy third-party analytics, but these systems can only assess the data that Google and Facebook choose to provide.",
    "expected_content" : "But this dominance has led to steadily increasing concern that advertisers themselves haven’t been able to independently evaluate Google’s reports of how ads perform on Google. Grading one’s own homework is problematic, critics say, because Google and Facebook both sell ads and give their partners the data to assess how well those ads may or may not be working. Advertisers can deploy third-party analytics, but these systems can only assess the data that Google and Facebook choose to provide."},
    {"type" : "text", "formatting" : "paragraph", "content" : "The setup means tech companies shoulder pretty much all of the responsibility—and embarrassment—if a measurement mistake comes to light. Facebook learned this the hard way when it revealed that it had erroneously @ over the past few months, from how much time users spent watching video clips to how many people visited publishers’ pages and how long they spent reading their articles.",
              "anchors" : [{"type" : "weblink","name" : "inflated several ad metrics" , "address" : "https://www.wired.com/2016/11/facebooks-stumbles-expose-flaws-plan-rule-advertising/" }],
              "expected_content": "The setup means tech companies shoulder pretty much all of the responsibility—and embarrassment—if a measurement mistake comes to light. Facebook learned this the hard way when it revealed that it had erroneously inflated several ad metrics over the past few months, from how much time users spent watching video clips to how many people visited publishers’ pages and how long they spent reading their articles."
    },
    // {"type" : "picture", "path" :  "/workspace/autotests/provisions/img/article2/Doodle.jpg"},
    // {"type" : "picture", "path" :  "/workspace/autotests/provisions/img/article2/GoogleSearch.png"},
    {"type" : "text", "formatting" : "paragraph", "content" : "Google seems to be hoping to avoid a similarly awkward situation. “If advertisers want to use our platforms, our stuff [should be] accredited, audited, and trustworthy,” says Babak Pahlavan, senior director of measurement at Google. “If they want to use third parties, we’re all for it. We love the idea of offering options, and they would be accredited also.” This opening up doesn’t mean Google is changing its process around how it currently measures metrics, nor does it mean that third-party measurement companies will get any more data from Google than they used to. But Google clearly hopes that the audit will alleviate concerns that its measurement process is in any way misleading. Still, Google isn’t likely to open up entirely for fear of giving away competitive advantages. Ultimately the question for advertisers will still come down to trust—and whether they think they can afford not to advertise on Google.",
    "expected_content" : "Google seems to be hoping to avoid a similarly awkward situation. “If advertisers want to use our platforms, our stuff [should be] accredited, audited, and trustworthy,” says Babak Pahlavan, senior director of measurement at Google. “If they want to use third parties, we’re all for it. We love the idea of offering options, and they would be accredited also.” This opening up doesn’t mean Google is changing its process around how it currently measures metrics, nor does it mean that third-party measurement companies will get any more data from Google than they used to. But Google clearly hopes that the audit will alleviate concerns that its measurement process is in any way misleading. Still, Google isn’t likely to open up entirely for fear of giving away competitive advantages. Ultimately the question for advertisers will still come down to trust—and whether they think they can afford not to advertise on Google."}
  ]
};
