exports.DOCUMENT =
{
  "meta":{
    "name" : ""
  },
  "sections":[
    {"text" : { "content" : "SUPER IDEA: A Rorschach Statement (No, This Isn’t Watchmen-Related)"}},
    {"text" : { "content" :"Kevin Feige spoke to Variety this week , and let a few tidbits slip, including the fact that Marvel is determined to find a female director for Captain Marvel, that the studio “wants” to be more progressive in terms of gender and racial diversity, and that recasting Captain America and Iron Man would be difficult, but not impossible. Perhaps most eye-catching, though, was his comment about whether Fox and Marvel could work together in the same way that Sony and Marvel do, and reboot the X-Men movies: “It’s an impossibility at this juncture.” But which part to focus on: “an impossibility,” which sounds particularly negative, or “at this juncture,” which… doesn’t…? Why this is super: It really is such a great way of seemingly appearing very firm, yet not actually saying anything much. File under: “Maybe some time in the future, then?”"}},
    {"text" : { "content" :"SUPER IDEA: Getting One of the John WickDirectors for Deadpool 2"}},
    {"text" : { "content" :"Hey, look: Deadpool 2 already has a new director ! Following the recent departure of Tim Miller, who helmed the first installment, David Leitch is now the new man in charge. Leitch is one of the two directors of John Wick, thereby confirming that the second Deadpool is likely to feature 100 percent more violence against dogs, but also some great stunt work, if there’s anything to be taken from Leitch’s resume to date. Why this is super: Leitch has been a name many have thrown around for superhero movies in the past—based, in large part, on his John Wick work—so it’ll be fascinating to see what he does now that he has the gig. Luckily, it’s a gig that would seem to play to his strengths, so good things should be forthcoming."}},
    {"text" : { "content" :"SUPER IDEA: Angela Bassett Joining Black Panther"}},
    {"text" : { "content" :"Because apparently the Black Panther movie can’t help but add new cast members, Angela Bassett has signed on to Ryan Coogler’s star-studded feature, with a role worthy of her talent: She’s going to play Ramonda, who just happens to be the Panther’s mother and the former Queen of Wakanda. So, you know, nothing special or anything. You’ll likely not even notice that she’s there. Why this is super: If this keeps up, Panther is going to have such an amazing cast that the other Marvel movies should just give up competing right now. Hell, all other superhero movies in general. Chadwick Boseman, Lupita Nyong’o, Michael B. Jordan, Danai Gurira, Forest Whitaker… That’s a ridiculously strong lineup of talent."}}//,
    // {"text" : "He calls his solution Mola. It’s the first structural modeling kit you’ll want to snap a selfie with, regardless of your major. Its sleek, sproingy parts beg to be played with and the subtle design belies the serious engineering concepts it so beautifully illustrates."},
    // {"text" : "SUPER IDEA: Lin-Manuel Miranda Playing a Spider-Man Villain"},
    // {"text" : "Let’s say that you’re the writer and star of one of the most successful musicals in modern memory, and you’ve stepped down from the role in search of new opportunities. Like, say, appearing in a Mary Poppins sequel or something. What do you do for an encore? Apparently, if you’re Lin-Manuel Miranda , the answer is suggest playing an obscure Spider-Man villain . According to rumor, the Hamilton creator is a big fan of the character Carnage , and would love to play him in a movie. Look, if Marvel and Sony want to turn the sequel to Spider-Man: Homecoming into a musical, we think there’s a smash hit movie somewhere in this idea. (Or maybe not .) Why this is super: Imagine the struggle going on inside Sony right now. On the one hand, Carnage is actually kind of a dull Venom rip-off. But on the other, it’s Lin-Manuel Miranda, who is beloved in a way that few other celebrities are right now. Do they bite the bullet and make plans for a Carnage-centric movie at some point in the near future, just in case, or hope that he could be convinced to play a villain with somewhat more credibility instead?"}
    ]
};
